language: node_js
node_js:
  - "lts/*"
install:
  - npm install
script:
  - npm run test
  - npm run build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: "build/"
    on:
      branch: development
  - provider: codedeploy
    revision_type: github
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: $AWS_APP_NAME
    deployment_group: $AWS_DEPLOYMENT_GROUP
    region: $AWS_REGION
    wait-until-deployed: true
    on:
      branch: development

branches:
  only:
  - development

