language: node_js
node_js:
  - "lts/*"
install:
  - npm install
script:
  - npm run test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: "build/"
  on:
    branch: development
branches:
  only:
  - development

